name: black

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.py"

jobs:
  black:
    name: black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: "."

      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with psf/black"
          commit-message: "fix: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in `${{ github.sha }}`. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }}
          branch: feat/black
          delete-branch: true
